augment2d:
  gridmask:
    fixed_prob: true
    prob: 0.0
  resize:
  - - 0.38
    - 0.55
  - - 0.48
    - 0.48
  rotate:
  - -5.4
  - 5.4
augment3d:
  rotate:
  - -0.78539816
  - 0.78539816
  scale:
  - 0.9
  - 1.1
  translate: 0.5
checkpoint_config:
  interval: 1
  max_keep_ckpts: 1
classes:
- road
- car
- truck
- pedestrian
- others
cudnn_benchmark: false
data:
  samples_per_gpu: 2
  test:
    ann_file: /data/carla/infos/carla_infos_test.pkl
    classes:
    - road
    - car
    - truck
    - pedestrian
    - others
    dataset_root: /data/carla/
    modality:
      use_camera: true
      use_lidar: true
    pipeline:
    - to_float32: true
      type: LoadMultiViewImageFromFiles
    - coord_type: LIDAR
      type: LoadCarlaPointsFromFile
    - bot_pct_lim:
      - 0.0
      - 0.0
      final_dim:
      - 256
      - 704
      is_train: false
      rand_flip: false
      resize_lim:
      - 0.48
      - 0.48
      rot_lim:
      - 0.0
      - 0.0
      type: ImageAug3D
    - is_train: false
      resize_lim:
      - 1.0
      - 1.0
      rot_lim:
      - 0.0
      - 0.0
      trans_lim: 0.0
      type: GlobalRotScaleTrans
    - type: LoadCarlaBEVSegmentation
    - point_cloud_range:
      - -51.2
      - -51.2
      - -5.0
      - 51.2
      - 51.2
      - 3.0
      type: PointsRangeFilter
    - mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      type: ImageNormalize
    - classes:
      - road
      - car
      - truck
      - pedestrian
      - others
      type: DefaultFormatBundle3D
    - keys:
      - img
      - points
      - gt_masks_bev
      meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix
      type: Collect3D
    test_mode: true
    type: CarlaDataset
  train:
    ann_file: /data/carla/infos/carla_infos_train.pkl
    classes:
    - road
    - car
    - truck
    - pedestrian
    - others
    dataset_root: /data/carla/
    modality:
      use_camera: true
      use_lidar: true
    pipeline:
    - to_float32: true
      type: LoadMultiViewImageFromFiles
    - coord_type: LIDAR
      type: LoadCarlaPointsFromFile
    - bot_pct_lim:
      - 0.0
      - 0.0
      final_dim:
      - 256
      - 704
      is_train: true
      rand_flip: true
      resize_lim:
      - 0.38
      - 0.55
      rot_lim:
      - -5.4
      - 5.4
      type: ImageAug3D
    - is_train: true
      resize_lim:
      - 0.9
      - 1.1
      rot_lim:
      - -0.78539816
      - 0.78539816
      trans_lim: 0.5
      type: GlobalRotScaleTrans
    - type: LoadCarlaBEVSegmentation
    - type: RandomFlip3D
    - point_cloud_range:
      - -51.2
      - -51.2
      - -5.0
      - 51.2
      - 51.2
      - 3.0
      type: PointsRangeFilter
    - mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      type: ImageNormalize
    - fixed_prob: true
      max_epoch: 20
      mode: 1
      offset: false
      prob: 0.0
      ratio: 0.5
      rotate: 1
      type: GridMask
      use_h: true
      use_w: true
    - type: PointShuffle
    - classes:
      - road
      - car
      - truck
      - pedestrian
      - others
      type: DefaultFormatBundle3D
    - keys:
      - img
      - points
      - gt_masks_bev
      meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix
      type: Collect3D
    test_mode: false
    type: CarlaDataset
  val:
    ann_file: /data/carla/infos/carla_infos_val.pkl
    classes:
    - road
    - car
    - truck
    - pedestrian
    - others
    dataset_root: /data/carla/
    modality:
      use_camera: true
      use_lidar: true
    pipeline:
    - to_float32: true
      type: LoadMultiViewImageFromFiles
    - coord_type: LIDAR
      type: LoadCarlaPointsFromFile
    - bot_pct_lim:
      - 0.0
      - 0.0
      final_dim:
      - 256
      - 704
      is_train: false
      rand_flip: false
      resize_lim:
      - 0.48
      - 0.48
      rot_lim:
      - 0.0
      - 0.0
      type: ImageAug3D
    - is_train: false
      resize_lim:
      - 1.0
      - 1.0
      rot_lim:
      - 0.0
      - 0.0
      trans_lim: 0.0
      type: GlobalRotScaleTrans
    - type: LoadCarlaBEVSegmentation
    - point_cloud_range:
      - -51.2
      - -51.2
      - -5.0
      - 51.2
      - 51.2
      - 3.0
      type: PointsRangeFilter
    - mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      type: ImageNormalize
    - classes:
      - road
      - car
      - truck
      - pedestrian
      - others
      type: DefaultFormatBundle3D
    - keys:
      - img
      - points
      - gt_masks_bev
      meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix
      type: Collect3D
    test_mode: false
    type: CarlaDataset
  workers_per_gpu: 4
dataset_root: /data/carla/
dataset_type: CarlaDataset
deterministic: false
evaluation:
  interval: 1
  pipeline:
  - to_float32: true
    type: LoadMultiViewImageFromFiles
  - coord_type: LIDAR
    type: LoadCarlaPointsFromFile
  - bot_pct_lim:
    - 0.0
    - 0.0
    final_dim:
    - 256
    - 704
    is_train: false
    rand_flip: false
    resize_lim:
    - 0.48
    - 0.48
    rot_lim:
    - 0.0
    - 0.0
    type: ImageAug3D
  - is_train: false
    resize_lim:
    - 1.0
    - 1.0
    rot_lim:
    - 0.0
    - 0.0
    trans_lim: 0.0
    type: GlobalRotScaleTrans
  - type: LoadCarlaBEVSegmentation
  - point_cloud_range:
    - -51.2
    - -51.2
    - -5.0
    - 51.2
    - 51.2
    - 3.0
    type: PointsRangeFilter
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: ImageNormalize
  - classes:
    - road
    - car
    - truck
    - pedestrian
    - others
    type: DefaultFormatBundle3D
  - keys:
    - img
    - points
    - gt_masks_bev
    meta_keys:
    - camera_intrinsics
    - camera2ego
    - lidar2ego
    - lidar2camera
    - camera2lidar
    - lidar2image
    - img_aug_matrix
    - lidar_aug_matrix
    type: Collect3D
fp16:
  loss_scale:
    growth_interval: 2000
gt_paste_stop_epoch: -1
image_size:
- 256
- 704
input_modality:
  use_camera: true
  use_lidar: true
load_from: null
log_config:
  hooks:
  - type: TextLoggerHook
  - type: TensorboardLoggerHook
  interval: 50
lr_config:
  policy: cyclic
max_epochs: 20
model:
  decoder:
    backbone:
      conv_cfg:
        bias: false
        type: Conv2d
      in_channels: 256
      layer_nums:
      - 5
      - 5
      layer_strides:
      - 1
      - 2
      norm_cfg:
        eps: 0.001
        momentum: 0.01
        type: BN
      out_channels:
      - 128
      - 256
      type: SECOND
    neck:
      in_channels:
      - 128
      - 256
      norm_cfg:
        eps: 0.001
        momentum: 0.01
        type: BN
      out_channels:
      - 256
      - 256
      type: SECONDFPN
      upsample_cfg:
        bias: false
        type: deconv
      upsample_strides:
      - 1
      - 2
      use_conv_for_no_stride: true
  encoders:
    camera:
      backbone:
        attn_drop_rate: 0.0
        convert_weights: true
        depths:
        - 2
        - 2
        - 6
        - 2
        drop_path_rate: 0.3
        drop_rate: 0.0
        embed_dims: 96
        init_cfg:
          checkpoint: pretrained/swint-nuimages-pretrained.pth
          type: Pretrained
        mlp_ratio: 4
        num_heads:
        - 3
        - 6
        - 12
        - 24
        out_indices:
        - 1
        - 2
        - 3
        patch_norm: true
        qk_scale: null
        qkv_bias: true
        type: SwinTransformer
        window_size: 7
        with_cp: false
      neck:
        act_cfg:
          inplace: true
          type: ReLU
        in_channels:
        - 192
        - 384
        - 768
        norm_cfg:
          requires_grad: true
          type: BN2d
        num_outs: 3
        out_channels: 256
        start_level: 0
        type: GeneralizedLSSFPN
        upsample_cfg:
          align_corners: false
          mode: bilinear
      vtransform:
        dbound:
        - 1.0
        - 60.0
        - 0.5
        downsample: 2
        feature_size:
        - 32
        - 88
        image_size:
        - 256
        - 704
        in_channels: 256
        out_channels: 80
        type: LSSTransform
        xbound:
        - -51.2
        - 51.2
        - 0.4
        ybound:
        - -51.2
        - 51.2
        - 0.4
        zbound:
        - -10.0
        - 10.0
        - 20.0
    lidar:
      backbone:
        block_type: basicblock
        encoder_channels:
        - - 16
          - 16
          - 32
        - - 32
          - 32
          - 64
        - - 64
          - 64
          - 128
        - - 128
          - 128
        encoder_paddings:
        - - 0
          - 0
          - 1
        - - 0
          - 0
          - 1
        - - 0
          - 0
          - - 1
            - 1
            - 0
        - - 0
          - 0
        in_channels: 3
        order:
        - conv
        - norm
        - act
        output_channels: 128
        sparse_shape:
        - 1024
        - 1024
        - 41
        type: SparseEncoder
      voxelize:
        max_num_points: 10
        max_voxels:
        - 90000
        - 120000
        point_cloud_range:
        - -51.2
        - -51.2
        - -5.0
        - 51.2
        - 51.2
        - 3.0
        voxel_size:
        - 0.1
        - 0.1
        - 0.2
  fuser:
    in_channels:
    - 80
    - 256
    out_channels: 256
    type: ConvFuser
  heads:
    map:
      classes:
      - road
      - car
      - truck
      - pedestrian
      - others
      grid_transform:
        input_scope:
        - - -51.2
          - 51.2
          - 0.8
        - - -51.2
          - 51.2
          - 0.8
        output_scope:
        - - -50
          - 50
          - 0.5
        - - -50
          - 50
          - 0.5
      in_channels: 512
      loss: focal
      type: BEVSegmentationHead
    object: null
  type: BEVFusion
momentum_config:
  policy: cyclic
optimizer:
  lr: 0.0001
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0
      relative_position_bias_table:
        decay_mult: 0
  type: AdamW
  weight_decay: 0.01
optimizer_config:
  grad_clip:
    max_norm: 35
    norm_type: 2
point_cloud_range:
- -51.2
- -51.2
- -5.0
- 51.2
- 51.2
- 3.0
resume_from: null
run_dir: runs/run-123db652-95981184
runner:
  max_epochs: 20
  type: CustomEpochBasedRunner
seed: 0
test_pipeline:
- to_float32: true
  type: LoadMultiViewImageFromFiles
- coord_type: LIDAR
  type: LoadCarlaPointsFromFile
- bot_pct_lim:
  - 0.0
  - 0.0
  final_dim:
  - 256
  - 704
  is_train: false
  rand_flip: false
  resize_lim:
  - 0.48
  - 0.48
  rot_lim:
  - 0.0
  - 0.0
  type: ImageAug3D
- is_train: false
  resize_lim:
  - 1.0
  - 1.0
  rot_lim:
  - 0.0
  - 0.0
  trans_lim: 0.0
  type: GlobalRotScaleTrans
- type: LoadCarlaBEVSegmentation
- point_cloud_range:
  - -51.2
  - -51.2
  - -5.0
  - 51.2
  - 51.2
  - 3.0
  type: PointsRangeFilter
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: ImageNormalize
- classes:
  - road
  - car
  - truck
  - pedestrian
  - others
  type: DefaultFormatBundle3D
- keys:
  - img
  - points
  - gt_masks_bev
  meta_keys:
  - camera_intrinsics
  - camera2ego
  - lidar2ego
  - lidar2camera
  - camera2lidar
  - lidar2image
  - img_aug_matrix
  - lidar_aug_matrix
  type: Collect3D
train_pipeline:
- to_float32: true
  type: LoadMultiViewImageFromFiles
- coord_type: LIDAR
  type: LoadCarlaPointsFromFile
- bot_pct_lim:
  - 0.0
  - 0.0
  final_dim:
  - 256
  - 704
  is_train: true
  rand_flip: true
  resize_lim:
  - 0.38
  - 0.55
  rot_lim:
  - -5.4
  - 5.4
  type: ImageAug3D
- is_train: true
  resize_lim:
  - 0.9
  - 1.1
  rot_lim:
  - -0.78539816
  - 0.78539816
  trans_lim: 0.5
  type: GlobalRotScaleTrans
- type: LoadCarlaBEVSegmentation
- type: RandomFlip3D
- point_cloud_range:
  - -51.2
  - -51.2
  - -5.0
  - 51.2
  - 51.2
  - 3.0
  type: PointsRangeFilter
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: ImageNormalize
- fixed_prob: true
  max_epoch: 20
  mode: 1
  offset: false
  prob: 0.0
  ratio: 0.5
  rotate: 1
  type: GridMask
  use_h: true
  use_w: true
- type: PointShuffle
- classes:
  - road
  - car
  - truck
  - pedestrian
  - others
  type: DefaultFormatBundle3D
- keys:
  - img
  - points
  - gt_masks_bev
  meta_keys:
  - camera_intrinsics
  - camera2ego
  - lidar2ego
  - lidar2camera
  - camera2lidar
  - lidar2image
  - img_aug_matrix
  - lidar_aug_matrix
  type: Collect3D
voxel_size:
- 0.1
- 0.1
- 0.2
